WebApplication1/WebApplication1/Models/BangSanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangSanPham
    {
        public int id { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public int Loai_id { get; set; }
        public int GiaBan { get; set; }
        public int GiaGoc { get; set; }
        public int GiaGop { get; set; }
        public int SoLuongTon { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/BangsanphamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Transactions;
namespace WebApplication1.Controllers
{
    public class BangsanphamController : Controller
    {
        private CS4PEEntities db = new CS4PEEntities();

        // GET: /Bangsanpham/
        public ActionResult Index()
        {
            var model = db.BangSanPhams.ToList();
            return View(model);
        }

        // GET: /Bangsanpham/Details/5
        public FileResult Details(int id)
        {
            var path = Server.MapPath("~/App_Data/" + id);
            return File(path, "images");
        }

        // GET: /Bangsanpham/Create
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }

        // POST: /Bangsanpham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( BangSanPham model)
        {
            //Tao điều kiện
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using(var scope = new TransactionScope())
                {
                db.BangSanPhams.Add(model);
                db.SaveChanges();

                var path = Server.MapPath("~/App_Data");
                path = path + "/" + model.id;
                if (Request.Files["HinhAnh"] != null && Request.Files["HinhAnh"].ContentLength > 0)
                {
                    Request.Files["HinhAnh"].SaveAs(path);
                    scope.Complete();
                    return RedirectToAction("Index");
                }
                else { ModelState.AddModelError("HinhAnh", "Chưa có hình ảnh"); }
                
                }
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }
        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
            {
                ModelState.AddModelError("GiaGoc", "Giá gốc phải lớn hơn 0");
            }
            if (model.GiaBan < model.GiaGoc)
            {
                ModelState.AddModelError("GiaGoc", "Giá gốc phải bé hơn giá bán");
            }
        }

        // GET: /Bangsanpham/Edit/5
        public ActionResult Edit(int id)
        {
            BangSanPham model = db.BangSanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // POST: /Bangsanpham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                    }
                    scope.Complete(); // approve for transaction
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // GET: /Bangsanpham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View(bangsanpham);
        }

        // POST: /Bangsanpham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            db.BangSanPhams.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Bangsanpham/Create.cshtml
@model WebApplication1.Models.BangSanPham

@{
    ViewBag.Title = "Tạo sản phẩm";
}

<h2>Thêm sản phẩm </h2>


@using (Html.BeginForm("Create", "Bangsanpham",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr/>
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "loại id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Loai_id", (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá trả góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng tồn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this)", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm sản phẩm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication1/WebApplication1/Views/Bangsanpham/Delete.cshtml
@model WebApplication1.Models.BangSanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BangSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/WebApplication1/Views/Bangsanpham/Details.cshtml
@model WebApplication1.Models.BangSanPham

@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết sản phẩm</h2>

<div>
    <h4>@Html.DisplayFor(model => model.TenSP)</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Mã sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Giá bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            Giá gốc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            Giá trả góp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            Số lượng tồn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            Loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", new { id = Model.id })" class="btn btn-warning">Sửa</a>
    <a href="@Url.Action("Index", new { id = Model.id })" class="btn btn-info">Quay lại</a>

</p>

WebApplication1/WebApplication1/Views/Bangsanpham/Edit.cshtml
@model WebApplication1.Models.BangSanPham

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh sửa</h2>


@using (Html.BeginForm("Edit", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BangSanPham</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSP)
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP)
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loai_id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Loai_id", String.Empty)
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan)
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaGoc)
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaGop)
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this)", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="@Url.Action("Details", new { id = Model.id })" width="300" height="200" />           
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication1/WebApplication1/Views/Bangsanpham/Index.cshtml
@using WebApplication1.Models
@model List<BangSanPham>
@{
    ViewBag.Title = "Sản phẩm";
}

<h2>Sản phẩm</h2>

<p>
    <a  href="@Url.Action("Create")" class="btn btn-success">Tạo sản phẩm</a>
</p>
<table id="BangSanPham" class="table table-hover">
    <thead>
        <tr>
            <th>
                Mã sản phẩm
            </th>
            <th>
                Tên sản phẩm
            </th>
            <th>
                Giá bán
            </th>
            <th>
                Giá gốc
            </th>
            <th>
                Giá trả góp
            </th>
            <th>
                Số lượng tồn
            </th>
            <th>
                Tên loại
            </th>
            <th>Hình sản phẩm</th>
            <th></th>
        </tr>
    </thead>

@foreach (var item in Model)
{
    <tbody>
        <tr>
            <td>
                @item.MaSP
            </td>
            <td>
                @item.TenSP
            </td>
            <td>
                @item.GiaBan.ToString("N0")
            </td>
            <td>
                @item.GiaGoc.ToString("N0")
            </td>
            <td>
                @item.GiaGop.ToString("N0")
            </td>
            <td>
                @item.SoLuongTon.ToString("N0")
            </td>
            <td>
                @item.LoaiSanPham.TenLoai
            </td>
            <td>
                <img src="@Url.Action("Details", new { id = item.id })" width="150" height="100" />
            </td>
            <td>

                <a title="Sửa" href="@Url.Action("Edit", new { id = item.id })" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                <a title="Xem" href="@Url.Action("Details", new { id = item.id })" class="btn btn-info"><span class="glyphicon glyphicon-search"></a>
                <a title="Xóa" href="@Url.Action("Delete", new { id = item.id })" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></a>

            </td>
        </tr>
    </tbody>
}

</table>

@section scripts{
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#BangSanPham').DataTable();
        });
    </script>
}